<a href="https://colab.research.google.com/github/umesh9883/python-programming/blob/main/Notebook_Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpylogo.svg

# Interview Kickstart

## Numpy Basics

Author: Anshaj Khare


---



In [1]:
import numpy as np

# How to create our first array

array_1 = np.array([1,2,3,4,5])

print(array_1)

[1 2 3 4 5]


In [ ]:
# Properties associated with our numpy array

print("Array 1, NDim:", array_1.ndim)
print("Array 1, Shape:", array_1.shape)
print("Array 1, Size:", array_1.size)
print("Array 1, Dtype:", array_1.dtype)

Array 1, NDim: 1
Array 1, Shape: (5,)
Array 1, Size: 5
Array 1, Dtype: int64


In [ ]:
array_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array 2")
print(array_2)

print("Array 2, Ndim:", array_2.ndim)
print("Array 2, Shape:", array_2.shape)
print("Array 2, Size:", array_2.size)
print("Array 2, Dtype:", array_2.dtype)

Array 2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Array 2, Ndim: 2
Array 2, Shape: (2, 5)
Array 2, Size: 10
Array 2, Dtype: int64


In [ ]:
# Reshaping the array

array_3 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print("Array 3")
print(array_3)
print('------')
print("After reshaping")
print(array_3.reshape(5,3))

Array 3
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
------
After reshaping
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
array_3.reshape(5,2)

ValueError: cannot reshape array of size 15 into shape (5,2)

In [ ]:
array_3.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
# Indexing and slicing numpy arrays

## Numpy indexing and slicing is the same as python lists

data = np.array([1,2,3])
data

array([1, 2, 3])

In [ ]:
data[0]

1

In [ ]:
data[1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
## Methods to create an array fast

np.zeros(10, dtype=np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# Adding and sorting elements in a numpy array

array_4 = np.array([2,1, 5, 10, 19, 12, 8, 15])

In [ ]:
np.sort(array_4)

array([ 1,  2,  5,  8, 10, 12, 15, 19])

In [ ]:
array_4

array([ 2,  1,  5, 10, 19, 12,  8, 15])

In [ ]:
## Arrays can be concatenated

x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])

print(x)
print('-----')
print(y)
print('-----')
print(np.concatenate((x, y), axis=0))

[[1 2]
 [3 4]]
-----
[[5 6]]
-----
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Basic Array Operations

array_5 = np.array([1,2])
array_6 = np.ones(2, dtype=int)

print(array_5)
print(array_6)

[1 2]
[1 1]


In [ ]:
array_5 + array_6

array([2, 3])

In [ ]:
array_5 - array_6

array([0, 1])

In [ ]:
array_5 * array_6

array([1, 2])

In [ ]:
## Summation of values in an array

array_7 = np.arange(2, 20, 2)
array_7

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array_7.sum()

90

In [ ]:
array_7.min()

2

In [ ]:
array_7.max()

18

In [ ]:
array_7.mean()

10.0

In [ ]:
# Broadcasting

array_8 = np.array([1, 3, 5, 9])

array_8 * 3.14

array([ 3.14,  9.42, 15.7 , 28.26])

In [ ]:
# Filtering in numpy arrays

array_9 = np.array([10, 12, 8, 4, 5, 1, 7, 22, 40, 6])

In [ ]:
array_9 > 20

array([False, False, False, False, False, False, False,  True,  True,
       False])

In [ ]:
array_9[array_9 > 20]

array([22, 40])

In [ ]:
array_9[array_9 <= 10]

array([10,  8,  4,  5,  1,  7,  6])

In [ ]:
array_9[(array_9 >= 10) & (array_9 <= 30 )]

array([10, 12, 22])

In [ ]:
# How to save and load numpy objects

array_10 = np.array([1,2,3,4,5,6,7,8])
array_10

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.save('tenth_array', array_10)

In [ ]:
! ls

sample_data  tenth_array.npy


In [ ]:
array_11 = np.load('tenth_array.npy')
array_11

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.savetxt('tenth_array_in_csv.csv', array_10)


In [ ]:
! ls

sample_data  tenth_array_in_csv.csv  tenth_array.npy


In [ ]:
! cat tenth_array_in_csv.csv

1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00


In [ ]:
array_12 = np.loadtxt('tenth_array_in_csv.csv')
array_12

array([1., 2., 3., 4., 5., 6., 7., 8.])